"""init tables

Revision ID: 7268d05ee4cc
Revises: 
Create Date: 2026-01-24 09:43:39.990602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7268d05ee4cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_county',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('state_abbr', sa.String(length=2), nullable=False),
    sa.Column('state_desc', sa.String(), nullable=False),
    sa.Column('county_name', sa.String(), nullable=False),
    sa.Column('total_population', sa.BigInteger(), nullable=True),
    sa.Column('total_pop_18_plus', sa.BigInteger(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_dim_county_geom ON dim_county USING gist (geom)")
    op.create_table('dim_measure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('measure_id', sa.String(), nullable=False),
    sa.Column('measure', sa.String(), nullable=False),
    sa.Column('data_value_type_id', sa.String(), nullable=False),
    sa.Column('data_value_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('short_question_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('measure_id', 'data_value_type_id', name='uq_measure_type')
    )
    op.create_table('fact_estimate_county',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('measure_dim_id', sa.Integer(), nullable=False),
    sa.Column('data_value', sa.Float(), nullable=True),
    sa.Column('low_confidence_limit', sa.Float(), nullable=True),
    sa.Column('high_confidence_limit', sa.Float(), nullable=True),
    sa.Column('footnote_symbol', sa.String(), nullable=True),
    sa.Column('footnote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['dim_county.location_id'], ),
    sa.ForeignKeyConstraint(['measure_dim_id'], ['dim_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'location_id', 'measure_dim_id', name='uq_year_county_measure')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_estimate_county')
    op.drop_table('dim_measure')
    op.drop_index('idx_dim_county_geom', table_name='dim_county', postgresql_using='gist')
    op.drop_table('dim_county')
    # ### end Alembic commands ###
